# Generated by Django 5.1.7 on 2025-03-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Комплектация')),
            ],
        ),
        migrations.CreateModel(
            name='Cvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='ObjemLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Обьем и лс')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('telephone', models.IntegerField(verbose_name='Номер телефона')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Модель')),
                ('foto', models.FileField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfdiller.comp', verbose_name='Комплектация')),
                ('cvet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfdiller.cvet', verbose_name='Цвет')),
                ('objemLS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfdiller.objemls', verbose_name='Обьем и лс')),
            ],
        ),
    ]
