# Generated by Django 5.1.7 on 2025-03-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfdiller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Модель')),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfdiller.model', verbose_name='Модель'),
        ),
    ]
