# Generated by Django 5.1.5 on 2025-03-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfdiller', '0002_model_alter_cars_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Modeli',
        ),
        migrations.AlterField(
            model_name='objemls',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Обьем и лс'),
        ),
    ]
