# Generated by Django 5.1.5 on 2025-03-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfdiller', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsvlad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=10000, verbose_name='Новость')),
            ],
        ),
    ]
