# Generated by Django 5.1.5 on 2025-03-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfdiller', '0005_newsvlad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRyad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('comp', models.ManyToManyField(to='appOfdiller.comp')),
                ('cvet', models.ManyToManyField(to='appOfdiller.cvet')),
                ('objemLS', models.ManyToManyField(to='appOfdiller.objemls')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfdiller.modeli', verbose_name='Модель')),
            ],
        ),
    ]
