# Generated by Django 5.1.5 on 2025-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfdiller', '0006_modelryad'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelryad',
            name='info',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Информация о модели'),
        ),
    ]
