# Generated by Django 5.1.5 on 2025-03-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfdiller', '0007_modelryad_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='prover',
            field=models.BooleanField(default=False, verbose_name='Обработка данных'),
        ),
    ]
