# Generated by Django 5.1.5 on 2025-03-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfdiller', '0009_alter_users_prover'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('telephone', models.IntegerField(verbose_name='Номер телефона')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('prover', models.BooleanField(verbose_name='Обработка данных')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfdiller.modeli', verbose_name='Модель')),
            ],
        ),
    ]
