# Generated by Django 5.1.5 on 2025-03-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOfdiller', '0010_testdrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvetModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('cvet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfdiller.cvet', verbose_name='Цвет')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOfdiller.modeli', verbose_name='Модель')),
            ],
        ),
    ]
